apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-api
  labels:
    app: baas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baas-api
  template:
    metadata:
      labels:
        app: baas-api
    spec:
      containers:
      - name: baas-api
        image: localhost:32000/baas-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-conf
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-conf
              key: MYSQL_DATABASE
        - name: REDIS_HOST
          value: redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: baas-api
spec:
  selector:
    app: baas-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP