# NGINX static html server and reverse proxy to /api for the baas service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: baas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: localhost:32000/website:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  labels:
    app: baas
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer